### ISSUE TITLE
Error on filter module after update

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#291]
I have this error after I updated. if I unpublish filter module website works.
![Image](https://github.com/user-attachments/assets/d2d3ef79-4d1b-4a52-93f6-0fddd44a2063)

**Comment by Giorgi625** [comment]
I checked and on 190 line to which error refers is reset buttons code

**Comment by Giorgi625** [comment]
there was written just \Text::_('CORESET'); and is needed \Joomla\CMS\Language\Text::_('CORESET'); to fix error.

**Comment by andiamine** [comment]
Fixed

**Comment by Giorgi625** [comment]
It is not fixed for me. I mean problem with resetting filter. 
Here you can 
https://joomla.ge/en/extensions on this page as you see in screenshot I have two filters set, both Type and Category are just multiple select fields and not built in Type or category of JoomCCK.
when I click on Reset button on module on the right collumn page just refreshes but nothing changes:

![Image](https://github.com/user-attachments/assets/e8938b90-3eba-4214-b25f-5822ad7e2278)
