### ISSUE TITLE
Class 'MModelBase' not found

### ISSUE THREAD

**Issue by Giorgi625** [JoomCoder-com/JoomCCK#39]
I get this error on frontpage if in published menu is published menuitem Joomcck >> Admin Dashboard
![modelbase](https://user-images.githubusercontent.com/16633699/230434468-f64fb497-72cb-41fb-b8f0-47ddce62ad85.png)

**Comment by andiamine** [comment]
Fixed, new update will be published now.

**Comment by LordHelmchen666** [comment]
Error still exists for me.

Attempted to load class "RouterRules" from namespace "Joomla\Component\Joomcck\Site\Service".
Did you forget a "use" statement for another namespace?

/components/com_joomcck/router.php:83
```
     * @param DatabaseInterface $db The database object
     */
    public function __construct(SiteApplication $app, AbstractMenu $menu)
    {
        parent::__construct($app, $menu);
        $this->attachRule(new \Joomla\Component\Joomcck\Site\Service\RouterRules($this));
    }

```

**Comment by Giorgi625** [comment]
I created new clean install and installed v2 but error still exist

**Comment by andiamine** [comment]
Strange , issue doesn't happen in our case.

**Comment by andiamine** [comment]
can you send me login details of website your are trying to install on, so i can test, you can send us login details on support@joomcoder.com

**Comment by Giorgi625** [comment]
> can you send me login details of website your are trying to install on, so i can test, you can send us login details on [support@joomcoder.com](mailto:support@joomcoder.com)

user details sent to email

**Comment by andiamine** [comment]
Fixed
